spring:
  application:
    name: scheduled-bot

  main:
    banner-mode: off

  cache:
    type: redis


  data:
    redis:
      host: localhost
      port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sa

  jpa:
    show-sql: true
    properties:
      hibernate:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          pool_size: 30
        show_sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: error
    com.howwow.schedulebot: error
    org.springframework: error
    org.hibernate: error

  logback:
    rollingpolicy:
      max-file-size: 50MB
      total-size-cap: 300MB
      max-history: 7

server:
  port: 8080

bot:
  token: ${TELEGRAM_BOT_TOKEN:...}
  name: ${TELEGRAM_BOT_NAME:...}