spring:
  application:
    name: scheduled-bot

  main:
    banner-mode: off

  cache:
    type: redis


  data:
    redis:
      host: localhost
      port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:sa}

  jpa:
    show-sql: true
    properties:
      hibernate:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          pool_size: 30
        show_sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

    com.howwow.schedulebot: warn
    org.springframework: WARN
    org.hibernate: ERROR

  file:
    name: logs/app.log
    path: /var/logs/myapp

  logback:
    rollingpolicy:
      max-file-size: 50MB
      total-size-cap: 300MB
      max-history: 7

server:
  port: 8080

bot:
  token: ${TELEGRAM_BOT_TOKEN:...}
  name: ${TELEGRAM_BOT_NAME:...}